### PR TITLE
Contao 3.x

### PR DESCRIPTION
**Pull request by may17**
This branch version is in build on top of the develop branch. It fixes some issues with contao 3.x. Also see the user feedback on the contao forum: https://community.contao.org/de/showthread.php?37196-mootoolsnav-auf-Contao-3-0-1

### CODE REVIEW

**Comment by aschempp** [comment]
I would love to hand over the extension to you if you need/use it? ;-)

**Comment by may17** [comment]
I don`t use the extension but there are some people out there that use it. Feel free to transfer the ownership :)

**Comment by aschempp** [comment]
Where should I transfer it to? And please request the ER transfer.

**Comment by may17** [comment]
please transfer it to me may17. I will request the ER transfer.

**Comment by aschempp** [comment]
I can't transfer it, because a repo with the same name already exists. Probably a fork. Can you rename it?

**Comment by may17** [comment]
Rename is complete

**Comment by aschempp** [comment]
now I get the message

> may17 already has a repository in the aschempp/contao-mootoolsnav network

looks like you need to remove your fork from github and apply the changes locally?

**Comment by may17** [comment]
woooooooooooar delete complete :D

**Pull request merged**
